spring:
  datasource:
      url: jdbc:mysql://127.0.0.1:3306/hive?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: hiveowner
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
      minIdle: 5
      maxActive: 100

       #下面为连接池补充设置
      initialSize: 5
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      poolPingEnabled: true
      poolPingQuery: "select 1"
      poolPingConnectionsNotUsedFor: 360000

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  #kafka配置
  kafka:
    #指定自己的kafka server地址
    bootstrap-servers: 192.168.83.115:9092,192.168.83.116:9092,192.168.83.117:9092

    producer:
      retries: 0
      batch-size: 1000
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 1

    consumer:
      #指定默认消费者group id
      group-id: "model_management"
      enable-auto-commit: "false"
    template:
      default-topic: modelMgrPf_02

kafka:
  topic:
    topic-name:
      -modelMgrPf_MXGL01
      -modelMgrPf_MXGL02

mybatis:
  mapper-locations: classpath:mapper/*.xml
  check-config-location: true
  type-aliases-package: me.walker.kafkademo